/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface": "#fff8f7",
        "primary-fixed-dim": "#eeb9bd",
        "secondary": "#615d5e",
        "surface-card": "#FFFFFF",
        "on-primary-fixed-variant": "#623c40",
        "outline": "#827474",
        "on-primary-container": "#6b4448",
        "surface-input-tint": "#EFF3FA",
        "on-background": "#1f1b1b",
        "primary-fixed": "#ffdadc",
        "surface-container-high": "#efe6e6",
        "surface-variant": "#eae0e0",
        "tertiary": "#476551",
        "primary-container": "#e8b4b8",
        "secondary-fixed": "#e8e1e2",
        "background-canvas-start": "#FDF2F4",
        "on-secondary-fixed-variant": "#494647",
        "on-surface-variant": "#504444",
        "surface-tint": "#7c5357",
        "surface-subtle": "#F6F7F9",
        "background": "#fff8f7",
        "status-danger": "#C44545",
        "on-primary-fixed": "#301216",
        "secondary-fixed-dim": "#cbc5c6",
        "status-warning": "#B87528",
        "primary": "#7c5357",
        "on-secondary-fixed": "#1d1b1c",
        "tertiary-container": "#a8c9b1",
        "on-tertiary-fixed": "#032111",
        "tertiary-fixed": "#c9ebd2",
        "background-canvas-end": "#F7D8DC",
        "text-body": "#4A4648",
        "on-secondary": "#ffffff",
        "secondary-container": "#e8e1e2",
        "on-surface": "#1f1b1b",
        "surface-bright": "#fff8f7",
        "surface-container-highest": "#eae0e0",
        "on-error-container": "#93000a",
        "accent-rose-hover": "#D89DA2",
        "on-tertiary-container": "#385542",
        "on-primary": "#ffffff",
        "inverse-primary": "#eeb9bd",
        "surface-container": "#f5eceb",
        "on-tertiary-fixed-variant": "#304d3b",
        "inverse-surface": "#342f2f",
        "border-soft": "#EBDCE0",
        "tertiary-fixed-dim": "#adceb6",
        "status-success": "#34795A",
        "surface-container-low": "#fbf1f1",
        "on-secondary-container": "#686364",
        "on-error": "#ffffff",
        "outline-variant": "#d4c2c3",
        "text-muted": "#7B7579",
        "surface-dim": "#e1d8d8",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f8efee",
        "error": "#ba1a1a",
        "text-heading": "#1F1B1D"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "1rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "margin": "2rem",
        "space-sm": "0.5rem",
        "space-2xl": "3rem",
        "gutter": "1.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-xl": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "label-xs": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-xl-mobile": ["30px", { lineHeight: "38px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "18px", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-xs": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}
